- name: Installing stow
  apt: name=stow
  tags:
    - install
    - dotfiles
    - stow
- name: Clone .dotfiles
  ansible.builtin.git:
    repo: 'https://github.com/ForAzens/.dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    update: yes
    recursive: yes
  tags:
    - install
    - dotfiles
    - stow
- name: Stow dotfiles
  shell: cd $HOME/.dotfiles && ./install
  tags:
    - install
    - dotfiles
    - stow
