- name: Installing stow
  apt: 
    name: stow
  become: yes
  tags:
    - install
    - dotfiles
    - stow

- name: Clone .dotfiles
  ansible.builtin.git:
    repo: 'https://github.com/ForAzens/.dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    update: yes
    recursive: yes
  tags:
    - install
    - dotfiles
    - stow

- name: Create folders to avoid collisions
  shell: mkdir -p ~/.config && mkdir -p ~/.local/bin
  tags:
    - install
    - dotfiles
    - stow

- name: Stow dotfiles
  shell: cd $HOME/.dotfiles && ./install
  tags:
    - install
    - dotfiles
    - stow
