- name: Install asdf golang plugin
  shell: zsh -ci 'asdf plugin add golang https://github.com/kennyp/asdf-golang.git'
  tags:
    - install
    - golang
    - neovim

- name: Install golang latest
  shell: zsh -ci 'asdf install golang latest'
  tags:
    - install
    - golang
    - neovim

- name: Set golang version global
  shell: zsh -ci 'asdf global golang latest'
  tags:
    - install
    - golang
    - neovim

