- name: Install nodejs asdf plugin
  shell: zsh -ci 'asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git 2> /dev/null'
  tags:
    - install
    - nodejs
    - neovim
  ignore_errors: yes

- name: Install node lts
  shell: zsh -ci 'asdf install nodejs lts'
  tags:
    - install
    - nodejs
    - neovim

- name: Set nodejs lts version global
  shell: zsh -ci 'asdf global nodejs lts'
  tags:
    - install
    - nodejs
    - neovim
