- name: Remove neovim
  shell: rm -rf ~/neovim
  tags:
    - install
    - neovim
- name: Clone neovim
  ansible.builtin.git:
    repo: 'https://github.com/neovim/neovim.git'
    dest: "{{ lookup('env', 'HOME') }}/neovim"
    version: "v0.8.0"
  tags:
    - install
    - neovim
- name: Build neovim
  shell: "cd {{ lookup('env', 'HOME') }}/neovim && make CMAKE_BUILD_TYPE=Release -j 20"
  tags: 
    - install
    - neovim
- name: Install neovim
  become: true
  shell: "cd {{ lookup('env', 'HOME') }}/neovim && make install"
  tags: 
    - install
    - neovim

- name: Install efm lang server
  shell: zsh -ci 'go install github.com/mattn/efm-langserver@latest'
  tags:
    - install
    - neovim

- name: Reshim golang asdf
  shell: zsh -ci 'asdf reshim golang'
  tags:
    - install
    - neovim

- name: Install node tools
  shell: zsh -ci 'npm install -g typescript typescript-language-server prettier @fsouza/prettierd eslint_d'
  tags:
    - install
    - neovim
