- name: Install zsh
  apt: name=zsh
  become: yes
  tags:
    - install
    - zsh

- name: Change shell
  shell: chsh -s `which zsh`
  become: yes
  tags:
    - install
    - zsh

- name: Install OhMyZsh
  shell: curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh | sh
  tags:
    - install
    - zsh

- name: Install zsh autosuggestions
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions'
    dest: "{{ lookup('env', 'HOME') }}/.oh-my-zsh/plugins/zsh-autosuggestions"
  tags:
    - install
    - zsh

- name: Remove default OhMyZsh .zshrc
  shell: rm $HOME/.zshrc
  tags:
    - install
    - zsh
